[package]
name = "fractal_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
iced = "0.8.0"
iced_core = "0.8.1"
iced_wgpu = "0.9.0"
iced_winit = "0.8.0"
wgpu = "0.15.1"
